### ISSUE TITLE
References have no date

### ISSUE THREAD

**Issue by kimbrianj** [Coleridge-Initiative/big-data-and-social-science#26]
A number of references have no date, and the citation shows "n.d." in the text. Any way to fix this?

**Comment by Juliaingridlane** [comment]
Are they mine? Lmk which ones and I’ll fix   Otherwise if for other authors
then the only way to fix is for them to go and get the bib citation again.

On Sat, Feb 15, 2020 at 1:07 PM Brian Kim <notifications@github.com> wrote:

> A number of references have no date, and the citation shows "n.d." in the
> text. Any way to fix this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Coleridge-2DInitiative_big-2Ddata-2Dand-2Dsocial-2Dscience_issues_26-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAD63AO5O7EAFRCBTDFFB5MDRDAVIBA5CNFSM4KV24V4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4INZHLTA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=NqIXSo-Qd97y4aHtYQuMl9sKuktVP8V4GWSmXuTypbw&s=dBtrINqsDXT2CVYoMS2zu5nRnBF-2V_7K64zEK-i6hI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD63AO4SD3CDUYSGD2R5ECDRDAVIBANCNFSM4KV24V4A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=NqIXSo-Qd97y4aHtYQuMl9sKuktVP8V4GWSmXuTypbw&s=58u0VZR3DUMx1_Cop8S0JHir2LoUtX8MdWrctaDArSE&e=>
> .
>
-- 
Julia Lane
Professor, Wagner School and Center for Urban Science and Progress
Provostial Fellow
Cell Phone 646 208 4990

**Comment by kimbrianj** [comment]
There's a few in the introduction. Looking at the first few paragraphs, there's (Kopf, n.d.), (Office of Management and Budget, n.d.),  (Hart, n.d.), at the end there's (SOSP, n.d.).

**Comment by Juliaingridlane** [comment]
Ok.  Will find them and fix.   Thanks for finding. Is first thing tomorrow
ok?

On Sat, Feb 15, 2020 at 1:22 PM Brian Kim <notifications@github.com> wrote:

> There's a few in the introduction. Looking at the first few paragraphs,
> there's (Kopf, n.d.), (Office of Management and Budget, n.d.), (Hart,
> n.d.), at the end there's (SOSP, n.d.).
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Coleridge-2DInitiative_big-2Ddata-2Dand-2Dsocial-2Dscience_issues_26-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAD63AOYSTGUYEF2LUBEHLUDRDAXEXA5CNFSM4KV24V4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL3TUPQ-23issuecomment-2D586627646&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=LJ2hpxXRbJhsW1cUw2VNqB34Ytpj20cwVbZhFkR6fd4&s=LC24qeDaFkrnusti58GsmUje4YKcTY-o5L9e5CRUSL4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD63AO67J6YT3UANAGLU5NDRDAXEXANCNFSM4KV24V4A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=LJ2hpxXRbJhsW1cUw2VNqB34Ytpj20cwVbZhFkR6fd4&s=uTZ9rv9rt_PHOWo-iNY9rNa8Nr_WNJj0NJZYhKBaL1c&e=>
> .
>
-- 
Julia Lane
Professor, Wagner School and Center for Urban Science and Progress
Provostial Fellow
Cell Phone 646 208 4990

**Comment by chkern** [comment]
I fixed some, but there are still a couple of "n.d."s left. They broadly fall into two categories:

- Links to websites (that we might want to include as links rather than as references)
- Software packages (for which we might find better references that do include a year).

For those we can't fix, however, "n.d." seems to be the proper APA solution:
https://apastyle.apa.org/learn/faqs/cite-website-material

**Comment by Juliaingridlane** [comment]
Thank you so much

Yes, I think put just links to websites – and for software, just also
provide a link



Thanks, Christoph



Julia Lane

Professor, Wagner and CUSP, NYU

Cell phone: 646 208 4990

https://coleridgeinitiative.org



*From:* Christoph Kern [mailto:notifications@github.com]
*Sent:* Tuesday, February 18, 2020 1:13 PM
*To:* Coleridge-Initiative/big-data-and-social-science <
big-data-and-social-science@noreply.github.com>
*Cc:* Juliaingridlane <julia.lane@nyu.edu>; Comment <
comment@noreply.github.com>
*Subject:* Re: [Coleridge-Initiative/big-data-and-social-science]
References have no date (#26)



I fixed some, but there are still a couple of "n.d."s left. They broadly
fall into two categories:

   - Links to websites (that we might want to include as links rather than
   as references)
   - Software packages (for which we might find better references that do
   include a year).
   For those we can't fix, however, "n.d." seems to be the proper APA
   solution:
   https://apastyle.apa.org/learn/faqs/cite-website-material
   <https://urldefense.proofpoint.com/v2/url?u=https-3A__apastyle.apa.org_learn_faqs_cite-2Dwebsite-2Dmaterial&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=ONFZVzm2FEGbWNGRnCKxedh5oCOV9cJc7-Tza9qthvw&s=pyM6lXPil8E6HziyD6QU3S-Ncj6JZv_MX46uPpABlGU&e=>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Coleridge-2DInitiative_big-2Ddata-2Dand-2Dsocial-2Dscience_issues_26-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAD63AO3ZWIT2CCX2XS7UYVDRDQQKPA5CNFSM4KV24V4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMDA4EI-23issuecomment-2D587599377&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=ONFZVzm2FEGbWNGRnCKxedh5oCOV9cJc7-Tza9qthvw&s=5uRb6izl3jUhSqVyhM2WN9fZadlBw8qxAIcayauhzBQ&e=>,
or unsubscribe
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AD63AOYIICQHNHCUABFXYDLRDQQKPANCNFSM4KV24V4A&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=omwcNBUqPba9pikmkXZXk2bFQ7zxZPhI5OH9dd8lFDA&m=ONFZVzm2FEGbWNGRnCKxedh5oCOV9cJc7-Tza9qthvw&s=KJdPSj4XSxfrqbEGCU5ihDY20-3CvObb1Z3EA9YXCeo&e=>
.
